PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS Track;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Artist;

CREATE TABLE Artist (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE,
    Country TEXT
);

CREATE TABLE Album (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    ReleaseYear INTEGER CHECK (ReleaseYear >= 1900),
    ArtistId INTEGER NOT NULL,
    FOREIGN KEY (ArtistId) REFERENCES Artist(Id) ON DELETE CASCADE
);

CREATE TABLE Track (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    DurationSeconds INTEGER NOT NULL CHECK (DurationSeconds > 0),
    AlbumId INTEGER NOT NULL,
    FOREIGN KEY (AlbumId) REFERENCES Album(Id) ON DELETE CASCADE
);